{"schemaVersion":{"patch":0,"minor":3,"major":0},"metadata":{"modules":[{"name":"WWDC Notes"}],"roleHeading":"WWDC20","role":"sampleCode","title":"Triage test failures with XCTIssue"},"abstract":[{"type":"text","text":"Put your test failures to work: Learn how to triage and diagnose uncaught issues in your app using the latest testing APIs in Xcode. We’ll show you how to help ease your testing workflow and put failures into context to help you deliver the best quality product."}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/wwdcnotes\/wwdc20-10687-triage-test-failures-with-xctissue"]}],"identifier":{"url":"doc:\/\/WWDCNotes\/documentation\/WWDCNotes\/WWDC20-10687-Triage-test-failures-with-XCTIssue","interfaceLanguage":"swift"},"primaryContentSections":[{"content":[{"anchor":"Overview","text":"Overview","level":2,"type":"heading"},{"inlineContent":[{"text":"Maintaining any active project requires investigating test failures, either locally or in Continuous Integration (CI). Investigating test failures requires answering the following questions:","type":"text"}],"type":"paragraph"},{"type":"unorderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"What failed?"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"How did it fail?","type":"text"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Why did it fail?"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"strong","inlineContent":[{"type":"text","text":"Where"}]},{"type":"text","text":" did it fail?"}]}]}]},{"inlineContent":[{"text":"Xcode 12 makes answering these questions more efficient. This talk covers the following 4 topics:","type":"text"}],"type":"paragraph"},{"type":"orderedList","items":[{"content":[{"inlineContent":[{"text":"Swift errors in tests","type":"text"}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Rich failure objects"}]}]},{"content":[{"inlineContent":[{"text":"Failure call stacks","type":"text"}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Advanced workflows"}]}]}]},{"anchor":"Presenting-Test-Failures-in-Xcode-12","text":"Presenting Test Failures in Xcode 12","level":2,"type":"heading"},{"anchor":"Issue-Navigator","text":"Issue Navigator","level":3,"type":"heading"},{"inlineContent":[{"text":"This is an example of a test failure. Notice how the annotation is gray. This indicates that the failure happened underneath the indicated line. On the left, the issue navigator shows a call stack under the failed test.","type":"text"}],"type":"paragraph"},{"inlineContent":[{"type":"image","identifier":"WWDC20-10687-gray_line"}],"type":"paragraph"},{"inlineContent":[{"text":"Clicking on a frame takes the source editor to that location. Now, the annotation is red because this is the actual source of the error.","type":"text"}],"type":"paragraph"},{"inlineContent":[{"type":"image","identifier":"WWDC20-10687-error_source"}],"type":"paragraph"},{"anchor":"Test-Report","text":"Test Report","level":3,"type":"heading"},{"inlineContent":[{"text":"The Test Report is another way to explore test failures, and is especially useful when working with the results of a CI failure.","type":"text"}],"type":"paragraph"},{"inlineContent":[{"type":"text","text":"Here, we can see a list of failing tests, each with a call stack. When you hover over a stack frame, you can see two buttons to the right. The Jump button, indicated with an arrow, jumps to the source of the error. The second button, called the Assistant button, is new in Xcode 12. This does the same thing as the Jump button, but opens a secondary editor next to the Test Report so you don’t have to go back and forth. Clicking on a different stack frame changes the secondary editor immediately."}],"type":"paragraph"},{"inlineContent":[{"type":"image","identifier":"WWDC20-10687-assistant_button"}],"type":"paragraph"},{"anchor":"1-Using-Swift-Errors-in-your-tests","text":"1. Using Swift Errors in your tests","level":2,"type":"heading"},{"inlineContent":[{"text":"XCTest makes it possible for test functions to throw. When a test does throw, the error is used to formulate the error message.","type":"text"}],"type":"paragraph"},{"inlineContent":[{"text":"This means you can replace boilerplate like this in your tests…","type":"text"}],"type":"paragraph"},{"syntax":"swift","code":["func testExample() {","  do {","    try codeThatThrows()","  } catch {","    XCTFail(\"\\(error)\")","  }","}"],"type":"codeListing"},{"inlineContent":[{"type":"text","text":"…with this:"}],"type":"paragraph"},{"syntax":"swift","code":["func testExample() throws {","  try codeThatThrows()","}"],"type":"codeListing"},{"inlineContent":[{"type":"text","text":"However, until recently, these failures could not provide the source code location for thrown errors in tests. That has now been fixed with the Swift runtime improvements in the following platforms:"}],"type":"paragraph"},{"items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"iOS and tvOS 13.4"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"macOS 10.15.4"}]}]}],"type":"unorderedList"},{"anchor":"Throwing-from-setUp-and-tearDown","text":"Throwing from setUp and tearDown","level":3,"type":"heading"},{"inlineContent":[{"text":"Similar improvements have also been brought to ","type":"text"},{"code":"setUp()","type":"codeVoice"},{"text":" and ","type":"text"},{"code":"tearDown()","type":"codeVoice"},{"text":".","type":"text"}],"type":"paragraph"},{"inlineContent":[{"type":"image","identifier":"WWDC20-10687-throwing_setup_teardown"}],"type":"paragraph"},{"anchor":"2-Rich-Failure-Objects","text":"2. Rich Failure Objects","level":2,"type":"heading"},{"inlineContent":[{"type":"text","text":"XCTest has always recorded test failures as 4 discrete values:"}],"type":"paragraph"},{"items":[{"content":[{"type":"paragraph","inlineContent":[{"text":"Failure message","type":"text"}]}]},{"content":[{"inlineContent":[{"text":"File path","type":"text"}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Line number where the failure was recorded"}]}]},{"content":[{"inlineContent":[{"text":"“Expected” flag to indicate if the failure was expected.","type":"text"}],"type":"paragraph"}]}],"type":"orderedList"},{"inlineContent":[{"text":"These values were passed into the ","type":"text"},{"type":"codeVoice","code":"recordFailure"},{"text":" API, which ensures that failures are logged and routed to Xcode for display:","type":"text"}],"type":"paragraph"},{"syntax":"swift","code":["open class XCTestCase: XCTest {","","  open func recordFailure(","    withDescription: String,","    inFile: String,","    atLine: Int,","    expected: Bool","  )","","}"],"type":"codeListing"},{"inlineContent":[{"type":"text","text":"In Xcode 12, these values have been encapsulated into a new struct "},{"code":"XCTIssue","type":"codeVoice"},{"type":"text","text":". This new type also adds:"}],"type":"paragraph"},{"items":[{"content":[{"inlineContent":[{"type":"text","text":"Distinct types"}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"text":"Detailed description","type":"text"}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"type":"text","text":"Associated error"}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"type":"text","text":"Attachments"}],"type":"paragraph"}]}],"type":"unorderedList"},{"anchor":"XCTAttachment","text":"`XCTAttachment`","level":3,"type":"heading"},{"items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Can capture arbitrary data"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Add this attachment to the test itself or an "},{"type":"codeVoice","code":"XCTActivity"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"codeVoice","code":"XCTIssue"},{"type":"text","text":" supports attachments, which allows customized diagnostics for test failures."}]}]}],"type":"unorderedList"},{"anchor":"Recording-XCTIssues","text":"Recording `XCTIssue`s","level":3,"type":"heading"},{"inlineContent":[{"type":"text","text":"There is a new API on "},{"type":"codeVoice","code":"XCTestCase"},{"type":"text","text":" for recording test failures, which is called by all types of asserts. The old "},{"type":"codeVoice","code":"recordFailure"},{"type":"text","text":" API has been deprecated."}],"type":"paragraph"},{"syntax":"swift","code":["open class XCTestCase: XCTest {","","  open func record(_ issue: XCTIssue)","","}"],"type":"codeListing"},{"anchor":"Modifying-issues","text":"Modifying issues","level":3,"type":"heading"},{"inlineContent":[{"type":"text","text":"In Swift, issues are immutable or mutable depending on your use of "},{"type":"codeVoice","code":"let"},{"type":"text","text":" or "},{"type":"codeVoice","code":"var"},{"type":"text","text":":"}],"type":"paragraph"},{"syntax":"swift","code":["let issue = XCTIssue(...)  \/\/ immutable","","var issue = XCTIssue(...)  \/\/ mutable"],"type":"codeListing"},{"inlineContent":[{"text":"In Objective-C, there is a special subclass for mutable issues which conforms to ","type":"text"},{"code":"NSMutableCopy","type":"codeVoice"},{"text":":","type":"text"}],"type":"paragraph"},{"syntax":"objectivec","code":["XCTIssue *issue = [[XCTIssue alloc] init ...];  \/\/ immutable","","XCTMutableIssue *mutableIssue = [issue mutableCopy];  \/\/ mutable"],"type":"codeListing"},{"anchor":"3-Failures-and-Source-Code","text":"3. Failures and Source Code","level":2,"type":"heading"},{"inlineContent":[{"type":"text","text":"One of the most important questions to answer about a test failure is “where did it happen?”."}],"type":"paragraph"},{"anchor":"Before-XCTIssue","text":"Before `XCTIssue`","level":3,"type":"heading"},{"inlineContent":[{"type":"text","text":"Core test failure data always included file path and line number, which is great for simple tests. This is not enough for functions that are shared by more than one test."}],"type":"paragraph"},{"inlineContent":[{"text":"Here are two tests calling the same shared function:","type":"text"}],"type":"paragraph"},{"syntax":"swift","code":["func testThingA() throws {","  let thing = Thing(\"a\")","  try assertProperties(for: thing)","}","","func testThingB() throws {","  let thing = Thing(\"b\")","  try assertProperties(for: thing)","}","","\/\/ Shared function","func assertProperties(for thing: Thing) throws {","  XCTAssertNotNil(thing.name)","  XCTAssertNotNil(thing.order)","}"],"type":"codeListing"},{"inlineContent":[{"type":"text","text":"Before, the test method would be marked as failing even though the failure occurred somewhere else. This has no further information to help the developer figure out "},{"type":"strong","inlineContent":[{"text":"where","type":"text"}]},{"type":"text","text":" the failure happened."}],"type":"paragraph"},{"inlineContent":[{"identifier":"WWDC20-10687-shared_failure","type":"image"}],"type":"paragraph"},{"inlineContent":[{"text":"This can be mitigated if the helper functions captures information from where it was invoked and explicitly uses that information in its assertion calls. However, if the helper has more than 1 assertion, there is now a different ambiguity: which assertion failed in the helper?","type":"text"}],"type":"paragraph"},{"inlineContent":[{"identifier":"WWDC20-10687-capture_helper","type":"image"}],"type":"paragraph"},{"anchor":"Now-with-XCTIssue","text":"Now with `XCTIssue`","level":3,"type":"heading"},{"inlineContent":[{"inlineContent":[{"type":"codeVoice","code":"XCTIssue"},{"type":"text","text":" captures and symbolicates call stacks"}],"type":"strong"},{"type":"text","text":" so the point of failure is more clear. Here, the same code now has a gray annotation to demonstrate that the failure happens lower in the call stack, and a red annotation where the failure actually occurs."}],"type":"paragraph"},{"inlineContent":[{"type":"image","identifier":"WWDC20-10687-failure_with_xctissue"}],"type":"paragraph"},{"inlineContent":[{"type":"text","text":"Most importantly, no extra effort was required to get this information."}],"type":"paragraph"},{"anchor":"4-Advanced-Workflows-with-new-APIs","text":"4. Advanced Workflows with new APIs","level":2,"type":"heading"},{"anchor":"Advanced-Workflow-1-Custom-Assertions","text":"Advanced Workflow 1: Custom Assertions","level":3,"type":"heading"},{"inlineContent":[{"text":"You can make your own assertions by creating ","type":"text"},{"code":"XCTIssue","type":"codeVoice"},{"text":" directly and then ","type":"text"},{"code":"record(_ issue:)","type":"codeVoice"},{"text":". In this example, the custom assertion validates some data and then includes the failure as an attachment to the issue that it records.","type":"text"}],"type":"paragraph"},{"syntax":"swift","code":["func assertSomething(","  about data: Data,","  file: StaticString = #filePath,","  line: UInt = #line",") {","  \/\/ Call out to custom validation function.","  guard !isValid(data) else { return }","","  \/\/ Create issue, declare with `var` for mutability.","  var issue = XCTIssue(type: .assertionFailure, compactDescription: \"Invalid data\")","","  \/\/ Attach the invalid data.","  issue.add(XCTAttachment(data: data))","","  \/\/ Capture the call site location as the point of failure.","  let location = XCTSourceCodeLocation(filepath: file, lineNumber: line)","  issue.sourceCodeContext = XCTSourceCodeContext(location: location)","","  \/\/ Record the issue.","  self.record(issue)","}"],"type":"codeListing"},{"anchor":"Advanced-Workflow-2-Overriding-record-issue","text":"Advanced Workflow 2: Overriding `record(_ issue:)`","level":3,"type":"heading"},{"inlineContent":[{"text":"You can observe, suppress, or modify failures recorded in your test class. This method is the funnel point through which all issues pass, so overrides have total control over the output of the test class.","type":"text"}],"type":"paragraph"},{"anchor":"Example-1-Overriding-for-Observation","text":"Example 1: Overriding for Observation","level":4,"type":"heading"},{"syntax":"swift","code":["override func record(_ issue: XCTIssue) {","  \/\/ Observe, introspect, log, etc:","  if shouldLog(issue) {","    print(\"I just observed an issue!\")","  }","","  \/\/ Don't forget to call super!","  super.record(issue)","}"],"type":"codeListing"},{"inlineContent":[{"type":"text","text":"You can also use "},{"type":"codeVoice","code":"XCTestObservationCenter"},{"type":"text","text":", but this approach is more useful if you only want to observe failures in one class."}],"type":"paragraph"},{"inlineContent":[{"type":"text","text":"If your override does "},{"inlineContent":[{"type":"text","text":"not"}],"type":"strong"},{"type":"text","text":" call "},{"code":"super","type":"codeVoice"},{"type":"text","text":", you will have suppressed the issue. It will not continue along the recording chain, and nothing will be sent to Xcode."}],"type":"paragraph"},{"syntax":"swift","code":["override func record(_ issue: XCTIssue) {","  \/\/ If you don't want to record it, just return.","  if shouldSuppress(issue) {","    return","  }","","  \/\/ Otherwise, pass it to `super`.","  super.record(issue)","}"],"type":"codeListing"},{"anchor":"Example-2-Overriding-for-Modification","text":"Example 2: Overriding for Modification","level":4,"type":"heading"},{"inlineContent":[{"type":"text","text":"This is the most common reason for overriding because you can add attachments, which can be great diagnostic aids."}],"type":"paragraph"},{"syntax":"swift","code":["override func record(_ issue: XCTIssue) {","  \/\/ Redeclare using `var` to enable mutation.","  var issue = issue","","  \/\/ Add a simple attachment.","  issue.add(XCTAttachment(string: \"hello\"))","","  \/\/ Pass it to `super`.","  super.record(issue)","}"],"type":"codeListing"},{"type":"heading","text":"Wrap Up","anchor":"Wrap-Up","level":2},{"type":"unorderedList","items":[{"content":[{"inlineContent":[{"type":"text","text":"Triaging test failures is important!"}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"text":"Call stacks help answer “where?”","type":"text"}],"type":"paragraph"},{"type":"unorderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"text":"This helps support more natural factoring of test code, such as code reuse and other best practices","type":"text"}]}]}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Attachments improve “how?” and “why?”"}]}]}]},{"type":"heading","text":"Written By","anchor":"Written-By","level":2},{"type":"row","numberOfColumns":5,"columns":[{"size":1,"content":[{"type":"paragraph","inlineContent":[{"type":"image","identifier":"skhillon"}]}]},{"size":4,"content":[{"anchor":"Sarthak-Khillon","level":3,"type":"heading","text":"Sarthak Khillon"},{"inlineContent":[{"type":"reference","overridingTitleInlineContent":[{"type":"text","text":"Contributed Notes"}],"overridingTitle":"Contributed Notes","identifier":"doc:\/\/WWDCNotes\/documentation\/WWDCNotes\/skhillon","isActive":true},{"type":"text","text":" "},{"type":"text","text":"|"},{"type":"text","text":" "},{"type":"reference","identifier":"https:\/\/github.com\/skhillon","isActive":true},{"type":"text","text":" "},{"type":"text","text":"|"},{"type":"text","text":" "},{"type":"reference","identifier":"https:\/\/x.com\/SarthakKhillon","isActive":true},{"type":"text","text":" "},{"type":"text","text":"|"},{"type":"text","text":" "},{"type":"reference","identifier":"https:\/\/www.linkedin.com\/in\/sarthakkhillon\/","isActive":true}],"type":"paragraph"}]}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"Missing anything? Corrections? "},{"identifier":"https:\/\/wwdcnotes.com\/documentation\/wwdcnotes\/contributing","type":"reference","isActive":true}]},{"type":"heading","text":"Related Sessions","anchor":"Related-Sessions","level":2},{"type":"links","style":"list","items":["doc:\/\/WWDCNotes\/documentation\/WWDCNotes\/WWDC20-10077-Eliminate-animation-hitches-with-XCTest","doc:\/\/WWDCNotes\/documentation\/WWDCNotes\/WWDC20-10091-Write-tests-to-fail","doc:\/\/WWDCNotes\/documentation\/WWDCNotes\/WWDC20-10164-XCTSkip-your-tests","doc:\/\/WWDCNotes\/documentation\/WWDCNotes\/WWDC20-10220-Handle-interruptions-and-alerts-in-UI-tests","doc:\/\/WWDCNotes\/documentation\/WWDCNotes\/WWDC20-10221-Get-your-test-results-faster"]},{"type":"small","inlineContent":[{"inlineContent":[{"type":"text","text":"Legal Notice"}],"type":"strong"}]},{"type":"small","inlineContent":[{"type":"text","text":"All content copyright © 2012 – 2024 Apple Inc. All rights reserved."},{"type":"text","text":" "},{"type":"text","text":"Swift, the Swift logo, Swift Playgrounds, Xcode, Instruments, Cocoa Touch, Touch ID, FaceID, iPhone, iPad, Safari, Apple Vision, Apple Watch, App Store, iPadOS, watchOS, visionOS, tvOS, Mac, and macOS are trademarks of Apple Inc., registered in the U.S. and other countries."},{"type":"text","text":" "},{"type":"text","text":"This website is not made by, affiliated with, nor endorsed by Apple."}]}],"kind":"content"}],"sections":[],"sampleCodeDownload":{"kind":"sampleDownload","action":{"identifier":"https:\/\/developer.apple.com\/wwdc20\/10687","type":"reference","isActive":true,"overridingTitle":"Watch Video (12 min)"}},"kind":"article","hierarchy":{"paths":[["doc:\/\/WWDCNotes\/documentation\/WWDCNotes","doc:\/\/WWDCNotes\/documentation\/WWDCNotes\/WWDC20"]]},"references":{"https://github.com/skhillon":{"identifier":"https:\/\/github.com\/skhillon","titleInlineContent":[{"type":"text","text":"GitHub"}],"title":"GitHub","url":"https:\/\/github.com\/skhillon","type":"link"},"WWDC20-Icon.png":{"identifier":"WWDC20-Icon.png","alt":null,"variants":[{"url":"\/images\/WWDC20-Icon.png","traits":["1x","light"]}],"type":"image"},"doc://WWDCNotes/documentation/WWDCNotes/WWDC20-10164-XCTSkip-your-tests":{"kind":"article","identifier":"doc:\/\/WWDCNotes\/documentation\/WWDCNotes\/WWDC20-10164-XCTSkip-your-tests","abstract":[{"text":"Get the test results that matter — and skip the ones that don’t. Discover how you can implement XCTSkip to conditionally avoid tests at runtime. We’ll take you through how to return this new test result and better document tests beyond pass and fail within your test bundle.","type":"text"}],"type":"topic","url":"\/documentation\/wwdcnotes\/wwdc20-10164-xctskip-your-tests","role":"sampleCode","title":"XCTSkip your tests"},"WWDC20-10687-assistant_button":{"identifier":"WWDC20-10687-assistant_button","alt":null,"variants":[{"url":"\/images\/WWDC20-10687-assistant_button.png","traits":["1x","light"]}],"type":"image"},"doc://WWDCNotes/documentation/WWDCNotes/skhillon":{"identifier":"doc:\/\/WWDCNotes\/documentation\/WWDCNotes\/skhillon","role":"sampleCode","abstract":[{"text":"No Bio on GitHub","type":"text"}],"url":"\/documentation\/wwdcnotes\/skhillon","kind":"article","type":"topic","title":"Sarthak Khillon (19 notes)","images":[{"identifier":"skhillon.jpeg","type":"card"},{"identifier":"skhillon.jpeg","type":"icon"}]},"doc://WWDCNotes/documentation/WWDCNotes/WWDC20":{"type":"topic","images":[{"identifier":"WWDC20-Icon.png","type":"icon"},{"identifier":"WWDC20.jpeg","type":"card"}],"title":"WWDC20","identifier":"doc:\/\/WWDCNotes\/documentation\/WWDCNotes\/WWDC20","kind":"article","abstract":[{"text":"Xcode 12, Swift 5.3, iOS 14, macOS 11 (Big Sur), tvOS 14, watchOS 7.","type":"text"},{"text":" ","type":"text"},{"text":"New APIs: ","type":"text"},{"type":"codeVoice","code":"WidgetKit"},{"type":"text","text":", "},{"type":"codeVoice","code":"StoreKit Testing"},{"type":"text","text":", and more."}],"url":"\/documentation\/wwdcnotes\/wwdc20","role":"collectionGroup"},"WWDC20-10687-throwing_setup_teardown":{"identifier":"WWDC20-10687-throwing_setup_teardown","alt":null,"variants":[{"url":"\/images\/WWDC20-10687-throwing_setup_teardown.png","traits":["1x","light"]}],"type":"image"},"doc://WWDCNotes/documentation/WWDCNotes":{"images":[{"type":"icon","identifier":"WWDCNotes.png"}],"type":"topic","url":"\/documentation\/wwdcnotes","role":"collection","title":"WWDC Notes","identifier":"doc:\/\/WWDCNotes\/documentation\/WWDCNotes","abstract":[{"type":"text","text":"Session notes shared by the community for the community."}],"kind":"symbol"},"WWDC20-10687-failure_with_xctissue":{"identifier":"WWDC20-10687-failure_with_xctissue","alt":null,"variants":[{"url":"\/images\/WWDC20-10687-failure_with_xctissue.png","traits":["1x","light"]}],"type":"image"},"https://developer.apple.com/wwdc20/10687":{"identifier":"https:\/\/developer.apple.com\/wwdc20\/10687","checksum":null,"url":"https:\/\/developer.apple.com\/wwdc20\/10687","type":"download"},"https://wwdcnotes.com/documentation/wwdcnotes/contributing":{"identifier":"https:\/\/wwdcnotes.com\/documentation\/wwdcnotes\/contributing","titleInlineContent":[{"type":"text","text":"Contributions are welcome!"}],"title":"Contributions are welcome!","url":"https:\/\/wwdcnotes.com\/documentation\/wwdcnotes\/contributing","type":"link"},"WWDC20-10687-error_source":{"identifier":"WWDC20-10687-error_source","alt":null,"variants":[{"url":"\/images\/WWDC20-10687-error_source.png","traits":["1x","light"]}],"type":"image"},"doc://WWDCNotes/documentation/WWDCNotes/WWDC20-10220-Handle-interruptions-and-alerts-in-UI-tests":{"type":"topic","url":"\/documentation\/wwdcnotes\/wwdc20-10220-handle-interruptions-and-alerts-in-ui-tests","abstract":[{"text":"Learn how to anticipate potential interruptions to your app’s interface and build smart tests to identify them. UI interruptions often appear indeterminately, typically during onboarding or first launch, which can make them hard to track down. Learn how to understand interruptions, write stronger tests with UI interruption handlers, and manage expected alerts.","type":"text"}],"role":"sampleCode","identifier":"doc:\/\/WWDCNotes\/documentation\/WWDCNotes\/WWDC20-10220-Handle-interruptions-and-alerts-in-UI-tests","kind":"article","title":"Handle interruptions and alerts in UI tests"},"WWDC20-10687-capture_helper":{"identifier":"WWDC20-10687-capture_helper","alt":null,"variants":[{"url":"\/images\/WWDC20-10687-capture_helper.png","traits":["1x","light"]}],"type":"image"},"doc://WWDCNotes/documentation/WWDCNotes/WWDC20-10091-Write-tests-to-fail":{"type":"topic","kind":"article","role":"sampleCode","url":"\/documentation\/wwdcnotes\/wwdc20-10091-write-tests-to-fail","identifier":"doc:\/\/WWDCNotes\/documentation\/WWDCNotes\/WWDC20-10091-Write-tests-to-fail","abstract":[{"text":"Plan for failure: Design great tests to help you find and diagnose even the toughest bugs. Learn how to improve your automated tests with XCTest to find hidden issues in even the best code. We’ll explain how to prepare your tests for failure to make triaging issues easier, letting you solve interface issues and deliver fixes quickly.","type":"text"}],"title":"Write tests to fail"},"https://x.com/SarthakKhillon":{"identifier":"https:\/\/x.com\/SarthakKhillon","titleInlineContent":[{"type":"text","text":"X\/Twitter"}],"title":"X\/Twitter","url":"https:\/\/x.com\/SarthakKhillon","type":"link"},"doc://WWDCNotes/documentation/WWDCNotes/WWDC20-10077-Eliminate-animation-hitches-with-XCTest":{"abstract":[{"type":"text","text":"Animations can dramatically enhance the user experience of your app, provide a sense of direct manipulation, and help people to better understand the results of their actions. Animation hitches can break that experience. Discover how to use XCTest to detect interruptions to smooth scrolling and animations, and learn how to catch regressions before they affect the people relying on your app."}],"url":"\/documentation\/wwdcnotes\/wwdc20-10077-eliminate-animation-hitches-with-xctest","kind":"article","identifier":"doc:\/\/WWDCNotes\/documentation\/WWDCNotes\/WWDC20-10077-Eliminate-animation-hitches-with-XCTest","title":"Eliminate animation hitches with XCTest","type":"topic","role":"sampleCode"},"WWDC20-10687-gray_line":{"identifier":"WWDC20-10687-gray_line","alt":null,"variants":[{"url":"\/images\/WWDC20-10687-gray_line.png","traits":["1x","light"]}],"type":"image"},"https://www.linkedin.com/in/sarthakkhillon/":{"identifier":"https:\/\/www.linkedin.com\/in\/sarthakkhillon\/","titleInlineContent":[{"type":"text","text":"Blog"}],"title":"Blog","url":"https:\/\/www.linkedin.com\/in\/sarthakkhillon\/","type":"link"},"skhillon.jpeg":{"identifier":"skhillon.jpeg","alt":null,"variants":[{"url":"\/images\/skhillon.jpeg","traits":["1x","light"]}],"type":"image"},"skhillon":{"identifier":"skhillon","alt":"Profile image of Sarthak Khillon","variants":[{"url":"\/images\/skhillon.jpeg","traits":["1x","light"]}],"type":"image"},"doc://WWDCNotes/documentation/WWDCNotes/WWDC20-10221-Get-your-test-results-faster":{"type":"topic","url":"\/documentation\/wwdcnotes\/wwdc20-10221-get-your-test-results-faster","abstract":[{"text":"Improve your testing suite to speed up your feedback loop and get fixes in faster. Learn more about the latest improvements to testing in Xcode, including how to leverage test plans, Xcodebuild updates, and APIs to eliminate never-ending and badly-behaved tests. We’ll explore Test Timeouts and Execution Time Allowances in XCTest, examine device parallelization, and detail recommended practices for balancing performance with clear fault localization.","type":"text"}],"role":"sampleCode","identifier":"doc:\/\/WWDCNotes\/documentation\/WWDCNotes\/WWDC20-10221-Get-your-test-results-faster","kind":"article","title":"Get your test results faster"},"WWDCNotes.png":{"identifier":"WWDCNotes.png","alt":null,"variants":[{"url":"\/images\/WWDCNotes.png","traits":["1x","light"]}],"type":"image"},"WWDC20.jpeg":{"identifier":"WWDC20.jpeg","alt":null,"variants":[{"url":"\/images\/WWDC20.jpeg","traits":["1x","light"]}],"type":"image"},"WWDC20-10687-shared_failure":{"identifier":"WWDC20-10687-shared_failure","alt":null,"variants":[{"url":"\/images\/WWDC20-10687-shared_failure.png","traits":["1x","light"]}],"type":"image"}}}